routes/web.php
<?php
use App\CourseTeacher;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.welcome');
})->name('root');

//Route::get('/admin', function () {
//    return view('admin.admin');
//});


Route::prefix('admin')->group(function(){

//    Route::view('/', 'admin.index')->name('dashboard');
    Route::resource('/dashboard', 'AdminController');
    Route::resource('teachers', 'TeacherController');
    Route::resource('courses', 'CourseController');
    Route::resource('students', 'StudentController');

});

app/Student.php
<?php

namespace App;
use App\Course;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{



    protected $fillable = [
        'teacher_id', 'name', 'email', 'contact', 'description', 'experience','dob', 'address', 'thumbnail',
    ];

    public function courses()
    {
        return $this->belongsToMany(Course::class, 'course_student', 'student_id', 'course_id');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\StudentValidationRequest;

use App\Course;
use App\Student;
use App\Teacher;


class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Student::all();
        $course = Course::all();
        return view('admin.students.index', compact('students', 'course'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $courses = Course::all();
        $teachers = Teacher::all();
        return view('admin.students.create', compact('courses', 'teachers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StudentValidationRequest $request)
    {
        try {
            $filename = sprintf('thumbnail_%s.jpg', random_int(1, 1000));
            if ($request->hasFile('thumbnail'))
                $filename = $request->file('thumbnail')->storeAs('teachers', $filename, 'public');

            $student = [
                'name' => $request->name,
                'email' => $request->email,
                'contact' => $request->contact,
                'description' => $request->description,
                'teacher_id' => $request->teacher,
                'experience' => $request->experience,
                'dob' => $request->dob,
                'address' => $request->address,
                'thumbnail' => $filename,
            ];

            $student = Student::create($student);
            $student->courses()->attach($request->input('course_id'));

            if ($student) {
                return redirect()->route('students.index')->with('success', 'Student Created successfully');

            }
        }catch (\Exception $exception){

            return redirect()
                ->route('students.index')
                ->with('error', 'There is an issue with your submission, please try again later.');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $student = Student::find($id);
        return view('admin.students.show', compact('student'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Student::find($id)->delete();

        return redirect()->route('students.index')->with('deleted','Students Deleted Successfully');
    }
}

resources/views/admin/students/create.blade.php
@extends('admin.layouts.app')
@section('title', 'teacher')

@push('stylesheets')

@endpush
@section('content')

<div class="col" style="margin-top: 50px">
    <div class="row">
        <div class="col-12 col-md-4">
            <h3 class="text-bold-500" style="font-weight: bold">Add New Student</h3>
        </div>
        <div class="col-12 col-md-8 text-right">
            <a href="{{ route('students.index') }}" class="btn btn-info">All Students</a>
        </div>
    </div>
    <form action="{{ route('students.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group col-xs-10 col-md-4 col-lg-4">
            <label for="name">Student Name</label>
            <input type="text" class="form-control" name="name" id="name">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('name')
                {{ $message }}
                @enderror</span>
        </div>
        <div class="form-group col-xs-10  col-md-4 col-lg-4">
            <label for="name">Email</label>
            <input type="email" class="form-control" name="email" id="email">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('email')
                {{ $message }}
                @enderror</span>
        </div>

        <div class="form-group col-xs-10 col-md-4 col-lg-4">
            <label for="name">Contact</label>
            <input type="text" class="form-control" name="contact" id="contact">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('contact')
                {{ $message }}
                @enderror</span>
        </div>

        <div class="form-group col-xs-10 col-md-12 col-lg-12">
        <label for="comment">Description:</label>
        <textarea class="form-control" rows="3" id="description" name="description"></textarea>
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('description')
                {{ $message }}
                @enderror</span>
        </div>



        <div class="form-group col-xs-10 col-md-12 col-lg-6">
            <label for="day">Select Course</label>
                <select style="text-transform: capitalize" class="form-control course" id="course_id" name="course_id" data-dependent="teacher">
                <option value="">Select Course</option>
              @if(!$courses->isEmpty())
                    @foreach($courses as $course)
                        <option value="{{$course->id}}">{{$course->name}}</option>
                    @endforeach
                @endif
            </select>
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('course_id')
                {{ $message }}
                @enderror</span>
        </div>

        <div class="form-group col-xs-10 col-md-12 col-lg-6">
            <label for="day">Select Teacher</label>
            <select  style="text-transform: capitalize" class="form-control" id="teacher" name="teacher">
                @if(!$teachers->isEmpty())
                    @foreach($teachers as $teacher)
                        <option value="{{$teacher->id}}">{{$teacher->name}}</option>
                    @endforeach
                @endif
            </select>
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('teacher')
                {{ $message }}
                @enderror</span>

        </div>
        <div class="form-group col-xs-10 col-md-4 col-lg-6">
            <label for="name">Experience</label>
            <input type="text" class="form-control" name="experience" id="experience">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('experience')
                {{ $message }}
                @enderror</span>
        </div>
        <div class="form-group col-xs-10 col-md-4 col-lg-6">
            <label for="name">Date of birth</label>
            <input type="date" class="form-control" name="dob" id="dob">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('dob')
                {{ $message }}
                @enderror</span>
        </div>
        <div class="form-group col-xs-10 col-md-4 col-lg-6">
            <label for="name">Address</label>
            <input type="text" class="form-control" name="address" id="address">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('address')
                {{ $message }}
                @enderror</span>
        </div>
        <div class="form-group col-xs-10 col-md-4 col-lg-6">
            <label for="name">Image</label>
            <input type="file" class="form-control" name="thumbnail" id="thumbnail">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('thumbnail')
                {{ $message }}
                @enderror</span>
        </div>


        <button type="submit" class="btn btn-info " style="width: 100%">Add new Student</button>
    </form>
</div>

@endsection


@push('scripts')

    <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>

    <script type="text/javascript">

        var jq = jQuery.noConflict();

        jq.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': jq('meta[name="csrf-token"]').attr('content')
            }
        });
        jq(document).ready(function () {

            jq('#course').on('change',function(e) {

                var teacher_id = e.target.value;
                jq.ajax({

{{--                    url:"{{ route('subcat') }}",--}}
                    type:"POST",
                    data: {
                        teacher_id: teacher_id
                    },

                    success:function (data) {
                        jq('#teacher').empty();
                        jq.each(data.teachers[0].teachers,function(index,teacher){

                            jq('#teacher').append('<option value="'+teacher.id+'">'+teacher.name+'</option>');
                        })
                    }
                })
            });
        });
    </script>

@endpush

resources/views/admin/students/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'Courses')

@push('stylesheets')

@endpush
@section('content')

    <div class="col" style="margin-top: 50px">
        <h4 style="margin-bottom: 30px;font-weight: bold">Edit  Course</h4>

        <form action="{{ route('teachers.update', $teacher->id) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group col-xs-10 col-md-4 col-lg-4">
                <label for="name">Teacher Name</label>
                <input type="text" class="form-control" name="name" id="name" value="{{$teacher->name}}" >
            </div>
            <div class="form-group col-xs-10  col-md-4 col-lg-4">
                <label for="name">Email</label>
                <input type="email" class="form-control" name="email" id="email" value="{{$teacher->email}}">
            </div>

            <div class="form-group col-xs-10 col-md-4 col-lg-4">
                <label for="name">Contact</label>
                <input type="text" class="form-control" name="contact" id="contact" value="{{$teacher->contact}}">
            </div>

            <div class="form-group col-xs-10 col-md-12 col-lg-12">
                <label for="comment">Description:</label>
                <textarea class="form-control" rows="3" id="description" name="description">{{$teacher->description}}
                </textarea>
            </div>

            <div class="form-group col-xs-10 col-md-12 col-lg-12">
                <label for="day">Select Course</label>
                <select selected  multiple="" class="form-control" id="course_id[]" name="course[]">
                    @foreach($course as $c)
                        <option value="{{ $c->id }}"   @foreach($teacher->courses as $cc){{$cc->pivot->course_id == $c->id ? 'selected': ''}}   @endforeach> {{ $c->name }}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group col-xs-10 col-md-4 col-lg-4">
                <label for="name">Experience</label>
                <input type="text" class="form-control" name="experience" id="experience" value="{{$teacher->experience}}">
            </div>

            <div class="form-group col-xs-10 col-md-4 col-lg-4">
                <label for="name">Address</label>
                <input type="text" class="form-control" name="address" id="address" value="{{$teacher->address}}">
            </div>

            <div class="form-group col-xs-10 col-md-4 col-lg-4">
                <label for="name">Image</label>
                <img width="7%" class="" src="{{ URL::asset('storage/'.$teacher->thumbnail) }}">
                <input type="file" class="form-control" name="thumbnail" id="thumbnail">
            </div>


            <button type="submit" class="btn btn-info " style="width: 100%">Update Teacher</button>
        </form>
    </div>

@endsection


@push('scripts')

@endpush

resources/views/admin/students/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Students')

@push('stylesheets')

@endpush
@section('content')
    <!-- Hoverable rows start -->
    <section class="section">
        <div class="row" id="table-hover-row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                       <div class="row">
                           <div class="col-12 col-md-4">
                               <h3 class="text-bold-500" style="font-weight: bold">All Students</h3>
                           </div>
                           <div class="col-12 col-md-8 text-right">
                               <a href="{{ route('students.index') }}" class="btn btn-info">All Students</a>
                               <a href="{{ route('students.create') }}" class="btn btn-info">Add New Students</a>
                           </div>
                       </div>
                    </div>
                    @if ($message = Session::get('error'))
                        <div class="alert alert-danger">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif
                    @if ($message = Session::get('deleted'))
                        <div class="alert alert-danger">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-content">
                        <div class="card-body">

                        </div>
                        <!-- table hover -->
                        @if(!$students->isEmpty())
                        <div class="table-responsive">
                            <table class="table table-hover mb-0">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
{{--                                    <th>Course</th>--}}
                                    <th>Email</th>
                                    <th>Contact</th>
                                    <th>Experience</th>
                                    <th>Image</th>
                                    <th>Dob</th>
                                    <th>ACTION</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($students as $student)
                                <tr>
                                    <td class="text-bold-500">{{ $student->id }}</td>
                                    <td class="text-bold-500">{{ $student->name }}</td>
{{--                                    <td class="text-bold-500">--}}
{{--                                            {{$teacher->CourseTeacher->id}}--}}

{{--                                    </td>--}}
                                    <td class="text-bold-500">{{ $student->email }}</td>
                                    <td class="text-bold-500">{{ $student->contact }}</td>
                                    <td class="text-bold-500">{{ $student->experience }}</td>
                                    <td class="text-bold-500"><img width="50" style="border-radius: 50%" height="50"  class="" src="{{ URL::asset('storage/'.$student->thumbnail) }}"></td>

                                    <td class="text-bold-500">{{ $student->dob }}</td>

                                      <td>
                                          <form action="{{ route('students.destroy',$student->id) }}" method="POST">
                                              <a class="btn btn-info" href="{{ route('students.show',$student->id) }}"><i class="fas fa-eye"></i></a>
                                              <a class="btn btn-success" href="{{ route('students.edit',$student->id) }}"><i class="fas fa-edit"></i></a>

                                              @csrf
                                              @method('DELETE')

                                              <button href="{{route('students.destroy', $student->id)}}"  type="submit" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                          </form>
                                      </td>
                                </tr>
                                @endforeach


                                </tbody>
                            </table>
                        </div>
                            @else
                            <div class=" p-3">
                                <p class="alert text-center alert-info font-weight-bold">No Students Available</p>
                            </div>

                            @endif
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hoverable rows end -->


@endsection


@push('scripts')

@endpush

resources/views/admin/students/show.blade.php
@extends('admin.layouts.app')
@section('title', 'show')

@push('stylesheets')



@endpush
<style>
    body {
        padding: 0;
        margin: 0;
        font-family: 'Lato', sans-serif;
        color: #000;
    }

    .student-profile .card {
        border-radius: 10px;
    }

    .student-profile .card .card-header .profile_img {
        width: 150px;
        height: 150px;
        object-fit: cover;
        margin: 10px auto;
        border: 10px solid #ccc;
        border-radius: 50%;
    }

    .student-profile .card h3 {
        font-size: 20px;
        font-weight: 700;
    }

    .student-profile .card p {
        font-size: 16px;
        color: #000;
    }

    .student-profile .table th,
    .student-profile .table td {
        font-size: 14px;
        padding: 5px 10px;
        color: #000;
    }
</style>
@section('content')
    <!-- Student Profile -->



    <div class="row" style="margin-top: 50px">
        <div class="col-lg-4">
            <div class="card shadow-sm">
                <div class="card-header bg-transparent text-center">
                    <img class="profile_img img-" style="border-radius: 158px;width: 160px;height: 160px; border: 13px solid #4e4e4e61;"
                         src="{{ URL::asset('storage/'.$student->thumbnail) }}" alt="">
                    <h3>{{$student->name}}</h3>
                </div>
                <div class="card-body" style="margin-top: 30px;">
                    <a role="button" href="{{route('students.edit', $student->id)}}" class="text-warning btn btn-success" style="width: 100%; margin: 5px 0">Edit</a>
                    <form action="{{route('students.destroy', $student->id)}}" method="post">
                        @csrf
                        @method('DELETE')
                        <button style="width: 100%; " role="button" href="{{route('students.destroy', $student->id)}}" class="text-danger btn btn-danger font-weight-bold-700">Delete</button>
                    </form>
                    <a role="button" href="{{route('students.index')}}" class="text-warning btn btn-info" style="width: 100%;"> <i class="fas fa-arrow-left"></i>  Back To Students</a>

                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="card shadow-sm">
                <div class="card-header bg- border-0">
                    <h3 class="mb-0" style="font-weight: bold; margin-bottom: 20px; text-align: center" ></i>{{$student->name}} - Information</h3>
                </div>
                <div class="card-body pt-0">
                    <table class="table table-bordered">
                        <tr>
                            <th width="30%">Email</th>
                            <td width="2%">:</td>
                            <td>{{$student->email}}</td>
                        </tr>
                        <tr>
                            <th width="30%">Contact	</th>
                            <td width="2%">:</td>
                            <td>{{$student->contact}}</td>
                        </tr>
                        <tr>
                            <th width="30%">Experience</th>
                            <td width="2%">:</td>
                            <td>{{$student->experience}} Year</td>
                        </tr>
                        <tr>
                            <th width="30%">Address</th>
                            <td width="2%">:</td>
                            <td>{{$student->address}}</td>
                        </tr>

                    </table>

                    {{--                    <tr>--}}
                    {{--                        <th width="30%"><h4 style="font-weight: bold; margin-bottom: 20px;">Course</h4></th>--}}
                    {{--                        <td> @foreach($teacher->courses as $course)<span style="background-color: darkgreen; color: #fff;--}}
                    {{--                            padding: 6px 8px; font-size: 12px; font-weight: bold; margin: 5px 3px; border-radius: 20px;">{{ $course->name }}</span>@endforeach</td>--}}
                    {{--                    </tr>--}}


                    <div style="border: 1px solid rgba(0,0,0,0.24); padding: 5px; margin-top: 40px">
                        <th width="30%"><h4 style="font-weight: bold">Description</h4></th>
                        <td>{{$student->description}}</td>
                    </div>


                </div>
            </div>
        </div>
    </div>

@endsection


@push('scripts')

@endpush