routes/web.php
<?php
use App\CourseTeacher;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.welcome');
})->name('root');

//Route::get('/admin', function () {
//    return view('admin.admin');
//});


Route::prefix('admin')->group(function(){

//    Route::view('/', 'admin.index')->name('dashboard');
    Route::resource('/dashboard', 'AdminController');
    Route::resource('teachers', 'TeacherController');
    Route::resource('courses', 'CourseController');
    Route::resource('students', 'StudentController');

});

resources/views/admin/courses/create.blade.php
@extends('admin.layouts.app')
@section('title', 'Courses')

@push('stylesheets')

@endpush
@section('content')

<div class="col" style="margin-top: 20px">

        <div class="row">
            <div class="col-12 col-md-4">
                <h3 class="text-bold-500" style="font-weight: bold">Add New Course</h3>
            </div>
            <div class="col-12 col-md-8 text-right">
                <a href="{{ route('courses.index') }}" class="btn btn-info">All courses</a>
                <a href="{{ route('courses.create') }}" class="btn btn-info">Add New Course</a>
            </div>
        </div>
    <form action="{{ route('courses.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="name">Course Name</label>
            <input type="text" class="form-control" name="name" id="name">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('name')
                {{ $message }}
                @enderror</span>
        </div>

        <label for="comment">Description:</label>
        <textarea class="form-control" rows="2" id="description" name="description"></textarea>
        <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('description')
            {{ $message }}
            @enderror</span>
        <div class="form-group">
            <label for="day">Select Days</label>
            <select  multiple="" class="form-control" id="day[]" name="day[]">
                <option value="mon">Monday</option>
                <option value="tue">Tuesday</option>
                <option value="wed">Wednesday</option>
                <option value="thur">Thursday</option>
                <option value="fri">Friday</option>
            </select>
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('day')
                {{ $message }}
                @enderror</span>

        </div>


        <div class="form-group col-xs-10 col-md-4 col-lg-6 ">
            <label for="name">Price (Pkr) </label>
            <input type="text" class="form-control" id="price" name="price">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('price')
                {{ $message }}
                @enderror</span>
        </div>

        <div class="form-group col-xs-10 col-md-4 col-lg-6 ">
            <label for="name">Discount (%)</label>
            <input type="text" class="form-control" id="discount" name="discount" value="0">
        </div>


        <div class="form-group col-xs-10 col-md-4 col-lg-6 ">
            <label for="name">Start Date $ Time</label>
            <input type="datetime-local" class="form-control" id="timefrom" name="start_time">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('start_time')
                {{ $message }}
                @enderror</span>
        </div>

        <div class="form-group col-xs-10 col-md-4 col-lg-6">
            <label for="name">End Date & Time</label>
            <input type="datetime-local" class="form-control" id="timeto" name="end_time">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('end_time')
                {{ $message }}
                @enderror</span>
        </div>

        <div class="form-group">
            <label for="thumbnail">Upload Image:</label>
            <input type="file" class="form-control" id="thumbnail" name="thumbnail">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('thumbnail')
                {{ $message }}
                @enderror</span>
        </div>

        <button type="submit" class="btn btn-info" style="width: 100%">Add New Course</button>
    </form>
</div>

@endsection


@push('scripts')

@endpush

resources/views/admin/courses/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'Courses')

@push('stylesheets')

@endpush
@section('content')

    <div class="col" style="margin-top: 50px">
      <div class="row">
          <div class="col-md-6">
              <h4 style="margin-bottom: 30px;font-weight: bold">Edit  Course</h4>
          </div>
          <div class="col-md-6" style="text-align: right">
              <a href="{{route('courses.index')}}" class="btn btn-info">Back to courses</a>
          </div>
      </div>

        <form action="{{ route('courses.update', $course->id) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="name">Course Name</label>
                <input type="text" class="form-control" name="name" id="name" value="{{$course->name}}">
                <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('name')
                    {{ $message }}
                    @enderror</span>
            </div>

            <label for="comment">Description:</label>
            <textarea class="form-control" rows="3" id="description" name="description">{{$course->description}}</textarea>
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('description')
                {{ $message }}
                @enderror</span>

            <div class="form-group">
                <label for="day">Select Days</label>
                <select  multiple="" class="form-control" id="day[]" name="day[]">
                    <option value="mon" @if(in_array('mon',$selectDays)) selected @endif>Monday</option>
                    <option value="tue" @if(in_array('tue',$selectDays)) selected @endif>Tuesday</option>
                    <option value="wed" @if(in_array('wed',$selectDays)) selected @endif>Wednesday</option>
                    <option value="thur" @if(in_array('thur',$selectDays)) selected @endif>Thursday</option>
                    <option value="fri" @if(in_array('fri',$selectDays)) selected @endif>Friday</option>
                </select>
                <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('day')
                    {{ $message }}
                    @enderror</span>
            </div>

            <div class="form-group col-xs-10 col-md-4 col-lg-6 ">
                <label for="name">Price (Pkr)</label>
                <input type="text" class="form-control" id="price" name="price"  value="{{$course->price}}">
                <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('price')
                    {{ $message }}
                    @enderror</span>
            </div>

            <div class="form-group col-xs-10 col-md-4 col-lg-6 ">
                <label for="name">Discount (%)</label>
                <input type="text" class="form-control" id="discount" name="discount"  value="{{$course->discount}}">
                <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('discount')
                    {{ $message }}
                    @enderror</span>
            </div>

            <div class="form-group col-xs-10 col-md-4 col-lg-6 ">
                <label for="name">Time From</label>
                <input type="datetime-local" class="form-control"
                       id="timefrom" name="start_time" value="{{ Carbon\Carbon::parse($course->start_time)->format('Y-m-d\TH:i') }}">
                <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('start_time')
                    {{ $message }}
                    @enderror</span>
            </div>

            <div class="form-group col-xs-10 col-md-4 col-lg-6">
                <label for="name">Time To</label>
                <input type="datetime-local" class="form-control"
                       id="timeto" name="end_time" value="{{ Carbon\Carbon::parse($course->end_time)->format('Y-m-d\TH:i') }}">
                <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('end_time')
                    {{ $message }}
                    @enderror</span>
            </div>

            <div class="form-group">
                <label for="thumbnail">Upload Image:</label>
                <img width="7%" class="" src="{{ URL::asset('storage/'.$course->thumbnail) }}">
                <input type="file" class="form-control" id="thumbnail" name="thumbnail">
                <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('thumbnail')
                    {{ $message }}
                    @enderror</span>
            </div>

            <button type="submit" class="btn btn-info" style="width: 100%">Update Course</button>
        </form>
    </div>

@endsection


@push('scripts')

@endpush

resources/views/admin/courses/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Courses')

@push('stylesheets')

@endpush
@section('content')
    <!-- Hoverable rows start -->
    <section class="section">
        <div class="row" id="table-hover-row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                       <div class="row">
                           <div class="col-12 col-md-4">
                               <h3 class="text-bold-500" style="font-weight: bold">All Courses</h3>
                           </div>
                           <div class="col-12 col-md-8 text-right">
                               <a href="{{ route('courses.index') }}" class="btn btn-info">All courses</a>
                               <a href="{{ route('courses.create') }}" class="btn btn-info">Add New Course</a>
                           </div>
                       </div>
                    </div>
                    @if ($message = Session::get('deleted'))
                        <div class="alert alert-danger">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    @if ($message = Session::get('error'))
                        <div class="alert alert-danger">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif
                    <div class="card-content">
                        <div class="card-body">

                        </div>
                        <!-- table hover -->
                        @if(!$courses->isEmpty())
                        <div class="table-responsive">
                            <table class="table table-hover mb-0">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Orignal Price</th>
                                    <th>Discount</th>
                                    <th>Sale Price</th>
                                    <th>Price</th>
                                    <th>ACTION</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($courses as $course)
                                <tr>
                                    <td class="text-bold-500">{{ $course->id }}</td>
                                    <td class="text-bold-500" style="text-transform: capitalize">{{ $course->name }}</td>

                                    @if($course->discount == 0 )
                                        <td class="text-bold-500">{{ $course->price }} Rs</td>
                                    @else
                                        <td class="text-bold-500" style="color: red"><del>{{ $course->price }}</del> Rs</td>
                                    @endif


                                    <td class="text-bold-500">{{ $course->discount }}%</td>
                                    <td class="text-bold-500"  style="color: #4c4c1e">{{ $course->sale_price }} Rs</td>

                                    @if(!$course->discount == 0 )
                                        <td class="text-bold-500"  style="color: green">{{ $course->sale_price }} Rs</td>
                                    @else
                                        <td class="text-bold-500"  style="color: green">{{ $course->price }} Rs</td>
                                    @endif

                                    <td>
                                        <form action="{{ route('courses.destroy',$course->id) }}" method="POST">
                                            <a class="btn btn-info" href="{{ route('courses.show',$course->id) }}" title="Show"><i class="fas fa-eye"></i></a>
                                            <a class="btn btn-success" href="{{ route('courses.edit',$course->id) }}" title="Edit"><i class="fas fa-edit"></i></a>
                                            @csrf
                                            @method('DELETE')
                                            <button href="{{route('courses.destroy', $course->id)}}" title="Delete"  type="submit" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach


                                </tbody>
                            </table>
                        </div>
                            @else
                            <div class=" p-3">
                                <p class="alert text-center alert-info font-weight-bold">No course Available</p>
                            </div>

                            @endif
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hoverable rows end -->


@endsection


@push('scripts')

@endpush

resources/views/admin/courses/show.blade.php
@extends('admin.layouts.app')
@section('title', 'show')

@push('stylesheets')



@endpush
<style>
    body {
        padding: 0;
        margin: 0;
        font-family: 'Lato', sans-serif;
        color: #000;
    }

    .student-profile .card {
        border-radius: 10px;
    }

    .student-profile .card .card-header .profile_img {
        width: 150px;
        height: 150px;
        object-fit: cover;
        margin: 10px auto;
        border: 10px solid #ccc;
        border-radius: 50%;
    }

    .student-profile .card h3 {
        font-size: 20px;
        font-weight: 700;
    }

    .student-profile .card p {
        font-size: 16px;
        color: #000;
    }

    .student-profile .table th,
    .student-profile .table td {
        font-size: 14px;
        padding: 5px 10px;
        color: #000;
    }
</style>
@section('content')
    <!-- Student Profile -->



    <div class="row" style="margin-top: 50px">
        <div class="col-lg-4">
            <div class="card shadow-sm">
                <div class="card-header bg-transparent text-center">
                    <img class="profile_img img-" style="border-radius: 158px;width: 160px;height: 160px; border: 13px solid #4e4e4e61;"
                         src="{{ URL::asset('storage/'.$course->thumbnail) }}" alt="">
                    <h3 style="text-transform: capitalize; font-weight: 600"> {{$course->name}}</h3>
                </div>
                <div class="card-body" style="margin-top: 30px;">
                    <a role="button" href="{{route('courses.edit', $course->id)}}" class="text-warning btn btn-success" style="width: 100%; margin: 5px 0">Edit</a>
                    <form action="{{route('courses.destroy', $course->id)}}" method="post">
                        @csrf
                        @method('DELETE')
                        <button style="width: 100%; " role="button" href="{{route('courses.destroy', $course->id)}}" class="text-danger btn btn-danger font-weight-bold-700">Delete</button>
                    </form>
                    <a role="button" href="{{route('courses.index')}}" class="text-warning btn btn-info" style="width: 100%;"> <i class="fas fa-arrow-left"></i>  Back To Courses</a>

                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="card shadow-sm">
                <div class="card-header bg- border-0">
                    <h3 class="mb-0" style="font-weight: bold; margin-bottom: 20px; text-align: center;background-color: #d51515; text-transform: capitalize;color: #fff;padding: 10px" ></i>
                      Course Name : <b>( {{$course->name}} )</b>  </h3>
                </div>
                <div class="card-body pt-0">
                    <table class="table table-bordered">
                        <tr>
                            <th width="30%">Days</th>
                            <td width="2%">:</td>
                            <td style="text-transform: capitalize">{{$course->day}}</td>
                        </tr>

                        <tr>
                            <th width="30%">Price</th>
                            <td width="2%">:</td>
                            <td>{{$course->price}} Rs</td>
                        </tr>
                        <tr>
                            <th width="30%">Discount</th>
                            <td width="2%">:</td>
                            <td>{{$course->discount}}%</td>
                        </tr>

                        <tr>
                            <th width="30%">Sale Price</th>
                            <td width="2%">:</td>
                            <td>{{$course->sale_price}}</td>
                        </tr>

                        <tr>
                            <th width="30%">Start Time</th>
                            <td width="2%">:</td>
                            <td>{{ Carbon\Carbon::parse($course->start_time)->format('d-M-y - g:i:s A' ) }}</td>
                        </tr>

                        <tr>
                            <th width="30%">End Time</th>
                            <td width="2%">:</td>
                            <td>{{ Carbon\Carbon::parse($course->end_time)->format('d-M-y - g:i:s A' ) }}</td>
                        </tr>
                        <tr>
                            <th width="30%">Description</th>
                            <td width="2%">:</td>
                            <td>{{$course->description}}</td>
                        </tr>


                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection


@push('scripts')

@endpush