routes/web.php
<?php
use App\CourseTeacher;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.welcome');
})->name('root');

//Route::get('/admin', function () {
//    return view('admin.admin');
//});


Route::prefix('admin')->group(function(){

//    Route::view('/', 'admin.index')->name('dashboard');
    Route::resource('/dashboard', 'AdminController');
    Route::resource('teachers', 'TeacherController');
    Route::resource('courses', 'CourseController');
    Route::resource('students', 'StudentController');

});

app/Teacher.php
<?php

namespace App;
use App\Course;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{


    protected $fillable = [
        'name', 'email', 'contact', 'description', 'experience','address', 'thumbnail',
    ];



    public function courses()
    {
        return $this->belongsToMany(Course::class, 'course_teacher', 'teacher_id', 'course_id');
    }

}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Database\Eloquent\Model;
use App\Http\Requests\TeacherValidationRequest;
use Illuminate\Http\Request;
use App\Teacher;
use App\Course;
use Carbon\Carbon;
class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teachers = Teacher::paginate(10);
        $course = Course::all();
        return view('admin.teachers.index', compact('teachers', 'course'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $courses = Course::all();
        return view('admin.teachers.create', compact('courses'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TeacherValidationRequest $request)
    {
        try {
            $filename = sprintf('thumbnail_%s.jpg', random_int(1, 1000));
            if ($request->hasFile('thumbnail'))
                $filename = $request->file('thumbnail')->storeAs('teachers', $filename, 'public');

            $teacher = [
                'name' => $request->name,
                'email' => $request->email,
                'contact' => $request->contact,
                'description' => $request->description,
                'experience' => $request->experience,
                'address' => $request->address,
                'thumbnail' => $filename,
            ];
            $teacher = Teacher::create($teacher);
            $teacher->courses()->attach($request->course);
            if ($teacher) {
                return redirect()->route('teachers.index')->with('success', 'Teacher Created successfully');
            }
        }catch (\Exception $exception){

            return redirect()
                ->route('teachers.index')
                ->with('error', 'There is an issue with your submission, please try again later.');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $teacher = Teacher::find($id);
        return view('admin.teachers.show', compact('teacher'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $teacher = Teacher::findOrFail($id);
        $course = Course::all();
        return view('admin.teachers.edit', compact('teacher','course'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $teachers =  Teacher::findOrFail($id);

        $filename = sprintf('thumbnail_%s.jpg', random_int(1,1000));
        if($request->hasFile('thumbnail')){
            $filename = $request->file('thumbnail')->storeAs('teachers', $filename,'public');
        }else{
            $filename = ($teachers['thumbnail']);
        }

        $teacher = [
            'name' => $request->name,
            'email' => $request->email,
            'contact' => $request->contact,
            'description' => $request->description,
            'experience' => $request->experience,
            'address' => $request->address,
            'thumbnail' => $filename,
        ];

        $teacher = $teachers->update($teacher);

        $teachers->courses()->sync($request->course);

        if($teacher){
            return redirect()->route('teachers.index')->with('success','Teacher Updated successfully');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Teacher::find($id)->delete();
        return redirect()->route('teachers.index')->with('deleted','Teacher deleted successfully');
    }
}

resources/views/admin/teachers/create.blade.php
@extends('admin.layouts.app')
@section('title', 'teacher')

@push('stylesheets')

@endpush
@section('content')

<div class="col" style="margin-top: 50px">
    <div class="row">
        <div class="col-12 col-md-4">
            <h3 class="text-bold-500" style="font-weight: bold">Add New Teacher</h3>
        </div>
        <div class="col-12 col-md-8 text-right">
            <a href="{{ route('teachers.index') }}" class="btn btn-info">All Teachers</a>
        </div>
    </div>
    <form action="{{ route('teachers.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group col-xs-10 col-md-4 col-lg-4">
            <label for="name">Teacher Name</label>
            <input type="text" class="form-control" name="name" id="name">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('name')
                {{ $message }}
                @enderror</span>
        </div>
        <div class="form-group col-xs-10  col-md-4 col-lg-4">
            <label for="name">Email</label>
            <input type="email" class="form-control" name="email" id="email">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('email')
                {{ $message }}
                @enderror</span>
        </div>

        <div class="form-group col-xs-10 col-md-4 col-lg-4">
            <label for="name">Contact</label>
            <input type="text" class="form-control" name="contact" id="contact">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('contact')
                {{ $message }}
                @enderror</span>
        </div>

        <div class="form-group col-xs-10 col-md-12 col-lg-12">
        <label for="comment">Description:</label>
        <textarea class="form-control" rows="3" id="description" name="description"></textarea>
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('description')
                {{ $message }}
                @enderror</span>
        </div>

        <div class="form-group col-xs-10 col-md-12 col-lg-12">
            <label for="day">Select Course</label>
            <select  multiple="" class="form-control" id="course[]" name="course[]">
              @if(!$courses->isEmpty())
                    @foreach($courses as $course)
                        <option value="{{$course->id}}">{{$course->name}}</option>
                    @endforeach
{{--                @else--}}
{{--                    <option value="No Course">No Course Available </option>--}}
                @endif
            </select>
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('course')
                {{ $message }}
                @enderror</span>
        </div>

        <div class="form-group col-xs-10 col-md-4 col-lg-4">
            <label for="name">Experience (Years) </label>
            <input type="text" class="form-control" name="experience" id="experience">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('experience')
                {{ $message }}
                @enderror</span>
        </div>

        <div class="form-group col-xs-10 col-md-4 col-lg-4">
            <label for="name">Address</label>
            <input type="text" class="form-control" name="address" id="address">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('address')
                {{ $message }}
                @enderror</span>
        </div>

        <div class="form-group col-xs-10 col-md-4 col-lg-4">
            <label for="name">Image</label>
            <input type="file" class="form-control" name="thumbnail" id="thumbnail">
            <span style="color: #ff0000; font-size: 13px; font-weight: bold">@error('thumbnail')
                {{ $message }}
                @enderror</span>
        </div>


        <button type="submit" class="btn btn-info " style="width: 100%">Add new Teacher</button>
    </form>
</div>

@endsection


@push('scripts')

@endpush

resources/views/admin/teachers/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'Courses')

@push('stylesheets')

@endpush
@section('content')

    <div class="col" style="margin-top: 50px">
        <h4 style="margin-bottom: 30px;font-weight: bold">Edit  Course</h4>

        <form action="{{ route('teachers.update', $teacher->id) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group col-xs-10 col-md-4 col-lg-4">
                <label for="name">Teacher Name</label>
                <input type="text" class="form-control" name="name" id="name" value="{{$teacher->name}}" >
            </div>
            <div class="form-group col-xs-10  col-md-4 col-lg-4">
                <label for="name">Email</label>
                <input type="email" class="form-control" name="email" id="email" value="{{$teacher->email}}">
            </div>

            <div class="form-group col-xs-10 col-md-4 col-lg-4">
                <label for="name">Contact</label>
                <input type="text" class="form-control" name="contact" id="contact" value="{{$teacher->contact}}">
            </div>

            <div class="form-group col-xs-10 col-md-12 col-lg-12">
                <label for="comment">Description:</label>
                <textarea class="form-control" rows="3" id="description" name="description">{{$teacher->description}}
                </textarea>
            </div>

            <div class="form-group col-xs-10 col-md-12 col-lg-12">
                <label for="day">Select Course</label>
                <select selected  multiple="" class="form-control" id="course_id[]" name="course[]">
                    @foreach($course as $c)
                        <option value="{{ $c->id }}"   @foreach($teacher->courses as $cc){{$cc->pivot->course_id == $c->id ? 'selected': ''}}   @endforeach> {{ $c->name }}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group col-xs-10 col-md-4 col-lg-4">
                <label for="name">Experience</label>
                <input type="text" class="form-control" name="experience" id="experience" value="{{$teacher->experience}}">
            </div>

            <div class="form-group col-xs-10 col-md-4 col-lg-4">
                <label for="name">Address</label>
                <input type="text" class="form-control" name="address" id="address" value="{{$teacher->address}}">
            </div>

            <div class="form-group col-xs-10 col-md-4 col-lg-4">
                <label for="name">Image</label>
                <img width="7%" class="" src="{{ URL::asset('storage/'.$teacher->thumbnail) }}">
                <input type="file" class="form-control" name="thumbnail" id="thumbnail">
            </div>


            <button type="submit" class="btn btn-info " style="width: 100%">Update Teacher</button>
        </form>
    </div>

@endsection


@push('scripts')

@endpush

resources/views/admin/teachers/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Teachers')

@push('stylesheets')

@endpush
@section('content')
    <!-- Hoverable rows start -->
    <section class="section">
        <div class="row" id="table-hover-row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                       <div class="row">
                           <div class="col-12 col-md-4">
                               <h3 class="text-bold-500" style="font-weight: bold">All Teachers</h3>
                           </div>
                           <div class="col-12 col-md-8 text-right">
                               <a href="{{ route('teachers.index') }}" class="btn btn-info">All Teacher</a>
                               <a href="{{ route('teachers.create') }}" class="btn btn-info">Add New Teacher</a>
                           </div>
                       </div>
                    </div>
                    @if ($message = Session::get('error'))
                        <div class="alert alert-danger">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif
                    @if ($message = Session::get('deleted'))
                        <div class="alert alert-danger">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-content">
                        <div class="card-body">

                        </div>
                        <!-- table hover -->
                        @if(!$teachers->isEmpty())
                        <div class="table-responsive">
                            <table class="table table-hover mb-0">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
{{--                                    <th>Course</th>--}}
                                    <th>Email</th>
                                    <th>Contact</th>
                                    <th>Experience</th>
                                    <th>Image</th>
                                    <th>ACTION</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($teachers as $teacher)
                                <tr>
                                    <td class="text-bold-500">{{ $teacher->id }}</td>
                                    <td class="text-bold-500">{{ $teacher->name }}</td>
{{--                                    <td class="text-bold-500">--}}
{{--                                            {{$teacher->CourseTeacher->id}}--}}

{{--                                    </td>--}}
                                    <td class="text-bold-500">{{ $teacher->email }}</td>
                                    <td class="text-bold-500">{{ $teacher->contact }}</td>
                                    <td class="text-bold-500">{{ $teacher->experience }} Year</td>
                                    <td class="text-bold-500"><img width="50" style="border-radius: 50%" height="50"  class="" src="{{ URL::asset('storage/'.$teacher->thumbnail) }}"></td>

                                      <td>
                                          <form action="{{ route('teachers.destroy',$teacher->id) }}" method="POST">
                                              <a class="btn btn-info" href="{{ route('teachers.show',$teacher->id) }}"><i class="fas fa-eye"></i></a>
                                              <a class="btn btn-success" href="{{ route('teachers.edit',$teacher->id) }}"><i class="fas fa-edit"></i></a>

                                              @csrf
                                              @method('DELETE')

                                              <button href="{{route('teachers.destroy', $teacher->id)}}"  type="submit" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                          </form>
                                      </td>
                                </tr>
                                @endforeach


                                </tbody>
                            </table>
                        </div>
                            @else
                            <div class=" p-3">
                                <p class="alert text-center alert-info font-weight-bold">No Teacher Available</p>
                            </div>

                            @endif
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hoverable rows end -->


@endsection


@push('scripts')

@endpush

resources/views/admin/teachers/show.blade.php
@extends('admin.layouts.app')
@section('title', 'show')

@push('stylesheets')



@endpush
<style>
    body {
        padding: 0;
        margin: 0;
        font-family: 'Lato', sans-serif;
        color: #000;
    }

    .student-profile .card {
        border-radius: 10px;
    }

    .student-profile .card .card-header .profile_img {
        width: 150px;
        height: 150px;
        object-fit: cover;
        margin: 10px auto;
        border: 10px solid #ccc;
        border-radius: 50%;
    }

    .student-profile .card h3 {
        font-size: 20px;
        font-weight: 700;
    }

    .student-profile .card p {
        font-size: 16px;
        color: #000;
    }

    .student-profile .table th,
    .student-profile .table td {
        font-size: 14px;
        padding: 5px 10px;
        color: #000;
    }
</style>
@section('content')
    <!-- Student Profile -->



    <div class="row" style="margin-top: 50px">
        <div class="col-lg-4">
            <div class="card shadow-sm">
                <div class="card-header bg-transparent text-center">
                    <img class="profile_img img-" style="border-radius: 158px;width: 160px;height: 160px; border: 13px solid #4e4e4e61;"
                         src="{{ URL::asset('storage/'.$teacher->thumbnail) }}" alt="">
                    <h3>{{$teacher->name}}</h3>
                </div>
                <div class="card-body" style="margin-top: 30px;">
                    <a role="button" href="{{route('teachers.edit', $teacher->id)}}" class="text-warning btn btn-success" style="width: 100%; margin: 5px 0">Edit</a>
                    <form action="{{route('teachers.destroy', $teacher->id)}}" method="post">
                        @csrf
                        @method('DELETE')
                        <button style="width: 100%; " role="button" href="{{route('teachers.destroy', $teacher->id)}}" class="text-danger btn btn-danger font-weight-bold-700">Delete</button>
                    </form>
                    <a role="button" href="{{route('teachers.index')}}" class="text-warning btn btn-info" style="width: 100%;"> <i class="fas fa-arrow-left"></i>  Back To Teachers</a>

                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="card shadow-sm">
                <div class="card-header bg- border-0">
                    <h3 class="mb-0" style="font-weight: bold; margin-bottom: 20px; text-align: center" ></i>{{$teacher->name}} - Information</h3>
                </div>
                <div class="card-body pt-0">
                    <table class="table table-bordered">
                        <tr>
                            <th width="30%">Email</th>
                            <td width="2%">:</td>
                            <td>{{$teacher->email}}</td>
                        </tr>
                        <tr>
                            <th width="30%">Contact	</th>
                            <td width="2%">:</td>
                            <td>{{$teacher->contact}}</td>
                        </tr>
                        <tr>
                            <th width="30%">Experience</th>
                            <td width="2%">:</td>
                            <td>{{$teacher->experience}} Year</td>
                        </tr>
                        <tr>
                            <th width="30%">Address</th>
                            <td width="2%">:</td>
                            <td>{{$teacher->address}}</td>
                        </tr>

                    </table>

                    <tr>
                        <th width="30%"><h4 style="font-weight: bold; margin-bottom: 20px;">Course</h4></th>
                        <td> @foreach($teacher->courses as $course)<span style="background-color: darkgreen; color: #fff;
                            padding: 6px 8px; font-size: 12px; font-weight: bold; margin: 5px 3px; border-radius: 20px;">{{ $course->name }}</span>@endforeach</td>
                    </tr>


                    <div style="border: 1px solid rgba(0,0,0,0.24); padding: 5px; margin-top: 40px">
                        <th width="30%"><h4 style="font-weight: bold">Description</h4></th>
                        <td>{{$teacher->description}}</td>
                    </div>


                </div>
            </div>
        </div>
    </div>

@endsection


@push('scripts')

@endpush